### ISSUE TITLE
Wrongly removed line breaks

### ISSUE THREAD

**Issue by datenreisender** [zkirkland/VSCodeFirstUpper#2]
When using `extension.capitalizeMarkDownTitles` on a markdown file line breaks were wrongly removed. E.g.

```markdown
# This is a title

This is text

Another paragraph
```

was turned into 

```markdown
# This Is a Title
This is textAnother paragraph
```

**Comment by zkirkland** [comment]
Whoops. Thank you for letting me know.

**Comment by zkirkland** [comment]
I am unable to reproduce this problem. I am using VS Code version 1.27.2 on Windows 10. I tried using keyboard shortcut and calling from the command menu. Both are working fine in my setup. Can you give me any particulars? (I realize this was a long time ago and I apologize for the late reply)

**Comment by datenreisender** [comment]
On my Mac the problem is still there but I just find out, that it only happens, if the file has LFs as line endings. With CRLF it does not happen. Maybe you can reproduce it with this?

**Comment by zkirkland** [comment]
Try it now. I think I fixed it. In `src/extension.ts`, line 115, I am using the `string.split()` function and I was splitting on the single character `\n`. I changed it to split on the RegExp `/\r?\n/`. I do not have a mac so hopefully it worked as intended.

**Comment by datenreisender** [comment]
Thanks, is fixed for me too!
