### ISSUE TITLE
Wrong capitalisation of “than”

### ISSUE THREAD

**Issue by datenreisender** [zkirkland/VSCodeFirstUpper#3]
I think, it is wrong, that “than” is in `FirstUpperForbiddenWords.txt`. E.g. in “More Than a Pun” it should be capitalised, e.g. according to https://capitalizemytitle.com/.

**Comment by zkirkland** [comment]
Hm... Interesting. I thought I was following Chicago style but according to the site you referenced, it should still be capitalized. I will fix this. Thanks!
